[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
libm = "0.2.7"

[dependencies.sdl2]
version = "*"
features = ["use_mac_framework", "image"]
